### PR TITLE
Fix syntax error in Menus.php

### PR DESCRIPTION
**Pull request by devlifeX**

### CODE REVIEW

**Comment by benfreke** [comment]
Thanks. Does this fix both #62 and #63 that you just raised? I'm on my phone right now, bit hard to check

**Comment by devlifeX** [comment]
No problem @benfreke, yes these fix #62 and #63.

**Comment by devlifeX** [comment]
@benfreke Use 6b60b6f instead 4c30a0d.

**Comment by benfreke** [comment]
Verified that it seems to happen on a fresh install. Thanks,

**Pull request merged**
